setw -g mode-keys vi

set -g status-style "bg=purple,fg=black"
set -g extended-keys on
setw -g mouse on

bind c new-window -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -v -c "#{pane_current_path}"

set -g @yank_action "copy-pipe"

